---
# data_path
data_path:
    train_data: "datasets/train.csv"
    test_data: "datasets/test.csv"


# model_path:
model_path:
    model_folderpath: "trained_model"

# model_features
all_features:
    numerical_features: 
    - Age
    - Fare
    - SibSp
    - Parch

    categotical_features:
    - Sex
    - Pclass

    drop_columns:
    - PassengerId
    - Name
    - Ticket
    - Cabin
    - Embarked


# training hyperparameters
train_hyperparameters:
    train_test_split : 0.20
    kfold: 5


# model parameters
all_models:
    # random_forest:
    #     classifier__n_estimators:
    #     - 50
    #     - 100
    #     - 200
    #     classifier__max_depth:
    #     - 10
    #     - 20
    #     - 30
    #     classifier__min_samples_split:
    #     - 2
    #     - 5
    #     - 10

    # svc:
    #     classifier__C:
    #     - 0.1
    #     - 1
    #     - 10
    #     classifier__gamma:
    #     - scale
    #     - auto
    #     classifier__kernel:
    #     - linear
    #     - rbf
    
    logisticregression:
        classifier__C:
        - 0.1
        - 1
        - 10
        classifier__penalty:
        - l2
        classifier__solver:
        - liblinear

        


...