---
# data_path
data_path:
    train_data: "datasets/train.csv"
    test_data: "datasets/test.csv"


# model_features
all_features:
    numerical_features: 
    - Age
    - Fare
    - SibSp
    - Parch

    categotical_features:
    - Sex
    - Pclass

    drop_columns:
    - PassengerId
    - Name
    - Ticket
    - Cabin
    - Embarked


# training hyperparameters
train_hyperparameters:
    train_test_split : 0.20
    kfold: 5


...